plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/drutmanl/Dropbox/Documents/2. Research Topics/2.3 Fusion/Fusion ABM/electoral reform game/third-party/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]